### ISSUE TITLE
Research client crash/server hang. 

### ISSUE THREAD

**Issue by brucethemoose** [Itszuvalex/Femtocraft-alpha-1#44]
Right clicking the "Micro Technology" item for the "Potentiality Harnessing" research consistently booted everyone from our SMP server.

I tried to replicate the bug in SP, but I didn't get any crash/error. 

So I removed several mods from the pack (Inpure Core, Journey Map, and Inventory Tweaks), logged back in, and the research worked fine without crashing the server. 

I'm not sure what caused the issue/crash, but I can't replicate the bug (as I already have the research). ATL log: (crashes happened towards the end, with all the inventory tweaks spam around midnight). 
http://paste.atlauncher.com/view/f4e0b6cf

Xaethon will post the server log in a bit.

**Comment by Itszuvalex** [comment]
Note:

Removed those mods from the client.  After doing so, it no longer booted people from the server.
Suggests Femto -> Inv Tweaks Clientside -> Inv Tweaks Serverside Interaction.
